package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.IncomeRecord;

import java.util.List;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Sat Nov 03 16:24:05 CST 2018
     */
    int updateByPrimaryKey(IncomeRecord record);

    /**
     * 查询收益时间与当前时间相等且收益状态为0的收益记录
     * @param incomeStatus
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByIncomeDateAndIncomeStatus(Integer incomeStatus);
}